# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-04 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_information', models.TextField(blank=True)),
                ('proof_of_insurance', models.TextField()),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='The phone number of an unregistered emergency contact. You must provide this if you do not link with a registered patient.', max_length=10, null=True)),
                ('emergency_contact', models.ForeignKey(blank=True, help_text='You have the option to link with a registered patient as an emergency contact.', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('account_type', models.CharField(choices=[('P', 'Patient'), ('A', 'Administrator'), ('D', 'Doctor'), ('N', 'Nurse')], max_length=1)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
