# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('instruction', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Doctor')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('results', models.TextField()),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.Diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='category',
            field=models.ManyToManyField(blank=True, to='medical.DiagnosisCategory'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='treatment_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.TreatmentSession'),
        ),
    ]
