# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_timestamp', models.DateTimeField(auto_now_add=True)),
                ('discharge_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Patient')),
                ('previous_session', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_session', to='hospital.TreatmentSession')),
                ('treating_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.Hospital')),
            ],
        ),
    ]
